### ISSUE TITLE
Documentation section on www.jabref.org

### ISSUE THREAD

**Issue by simonharrer** [JabRef/www.jabref.org#1]
"Documentation" should part of the header.

**Comment by koppor** [comment]
How should it be realized?

Option A: Merge with "Support"?

![grabbed_20160127-140232](https://cloud.githubusercontent.com/assets/1366654/12614259/09cf5af8-c4ff-11e5-8d05-ade2befa1ecd.png)

Option B: Directly jump to help.jabref.org? But this is inconsistent as that field in the header had different semantics.

Option C: Separate section "Documentation" in the homepage.

But then, it would be a one line pointing to help.jabref.org

Option D: Rename "Support" to "Documentation"

Also not quite matching

**Comment by simonharrer** [comment]
C

**Comment by koppor** [comment]
Adressed at 689419e. Does http://www.jabref.org/#documentation fit your expectations?

**Comment by simonharrer** [comment]
Awesome.
