### ISSUE TITLE
FAQ: General: Issues with some Q&A

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#10]
I have updated/cleaned/clarified the file _faq/10_general.md .
However, 2 Question&Answer need your input. 
The issues are indicated by text between square brackets at the beginning of the questions.

**Comment by koppor** [comment]
`[Which version?]`: I think, this is possible since 2.10 or so. Why is that important. All other FAQs are also applicable to the latest version only, aren't they?

`[How can it be opened?]`: A double click on the `jar` file. Added it to the text.

**Comment by mlep** [comment]
> [Which version?]: I think, this is possible since 2.10 or so. Why is that important. All other FAQs are also applicable to the latest version only, aren't they?

The answer mentions "in the upcoming version", meaning the user has to wait...
So, I am going to reword the answer a bit.

> [How can it be opened?]: A double click on the jar file. Added it to the text.

OK, I will clarify this.

**Comment by mlep** [comment]
Done
