### ISSUE TITLE
"The OAuth client was deleted" on discourse.jabref.org

### ISSUE THREAD

**Issue by szhorvat** [JabRef/www.jabref.org#104]
When I try to register on https://discourse.jabref.org/ using Google, I get this error message:

![image](https://user-images.githubusercontent.com/1212871/87557469-3c873f00-c6b8-11ea-8b7f-4809991092b6.png)

Happens both in Firefox and Chrome.

I hope this is the right place to report this.

**Comment by koppor** [comment]
Follow up at https://github.com/JabRef/jabref/issues/6727
