### ISSUE TITLE
Getting started: dead link

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#109]
On the section about support (https://www.jabref.org/#support), the "getting started" link is dead. Too bad for newcomers. :-/

About getting started with JabRef, a good video tutorial: https://www.youtube.com/watch?v=11qMBE_PSBw
Where to advertise it?

**Comment by tobiasdiez** [comment]
Thanks for the pointer!

Looks like the commit https://github.com/JabRef/user-documentation/commit/54f288095234b6a9de2e9abfece1c558cebf8e2f reverted a lot of the recent changes. @koppor was this on purpose?

**Comment by koppor** [comment]
We ported the switch to the `main` branch also to GitBook.

@tobiasdiez I am not sure whether this is really a revert or not. My first check was that the new text reads better, but maybe, that new text was the old text by me and I just did not follow updates happening afterwards.

My check was based on the following observation:

![grafik](https://user-images.githubusercontent.com/1366654/118734394-93145b00-b83e-11eb-87c4-8c2f08976979.png)

However, that change seems that there is a revert:

![grafik](https://user-images.githubusercontent.com/1366654/118734634-1a61ce80-b83f-11eb-9c2b-ab887ec4a4f2.png)


And @mlep is now starting to modify pages again. (See https://github.com/JabRef/user-documentation/commits/main)

I have no clue, what to do now. Just restore the page as of April 10th 2021 and then try to port all changes afterwards to that?

**Comment by koppor** [comment]
This also refs https://github.com/JabRef/jabref/pull/7750/files

**Comment by tobiasdiez** [comment]
I think the whole commit is reverting to something really old. The text at the beginning in the readme is essentially our standard advertisement text, but we do not need to advertise jabref in the documentation. These "strange comments" are special gitbook links (that are displayed as blocks). It seems it is safe to revert this commit completely. Probably gitbook got confused with the branches and restored an old version.

**Comment by koppor** [comment]
"Really old" is c1bfa8a425473a59919a5a7236bf454bbf7862ae (of 2021-01-2024), because there `main` and `master` diverge. --> we had both `main` and `master`.

I just merged `main` into `master` (without taking any data from `main`) and pushed it as new `main`. Should be "good enough".

**Comment by tobiasdiez** [comment]
Thanks Olly!
