### ISSUE TITLE
Site is broken

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/www.jabref.org#11]
Site is currently totally broken:
![jabref org](https://cloud.githubusercontent.com/assets/676652/12747026/ebc0ba1e-c9a1-11e5-8d39-fa9f27297b6a.png)

**Comment by koppor** [comment]
I have no clue. It works fine locally and regenerating the site does not change anything.

**Comment by oscargus** [comment]
I can confirm that is index.html as obtained from wget without any redirects...

**Comment by matthiasgeiger** [comment]
Maybe related to https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0 ?

**Comment by koppor** [comment]
Confirmed. With `bundle update` I get the Jekyll version breaking the whole page.

**Comment by mlep** [comment]
Yesterday evening, I received the following email. I believe this is unrelated, but I have not the skills to decide about it...

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The page build completed successfully, but returned the following warning:

You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions you can contact us by replying to this email.

**Comment by koppor** [comment]
The theme we base on (https://github.com/t413/SinglePaged) is also broken.

**Comment by mlep** [comment]
Seems to be working again!

**Comment by matthiasgeiger** [comment]
This means, that Olly is fond of those startups and wants to support them. ;-)

@koppor As I understand it, your fix was not quick'n'dirty but actually solving the issue - thus I'm closing here.
