### ISSUE TITLE
bug in "Export"

### ISSUE THREAD

**Issue by wujastyk** [JabRef/www.jabref.org#12]
Jabref 3.2, running on Linux Mint + Cinnamon 17.3. 

> $java -version
> java version "9-ea"
> Java(TM) SE Runtime Environment (build 9-ea+102-2016-01-21-001533.javare.4316.nc)
> Java HotSpot(TM) 64-Bit Server VM (build 9-ea+102-2016-01-21-001533.javare.4316.nc, mixed mode)

When I try to Export my 3000 entry database from the main File menu, using the "HTML Table (with Abstract and bibtex)" export filter, I get a java NullPointerException error and the export doesn't take place.  See this graphic of the error:

![jabref error](https://cloud.githubusercontent.com/assets/762246/12763532/230a92fa-c9b2-11e5-8274-f24d754a23e0.png)

**Comment by koppor** [comment]
Thank you for the report. Unfortunately, your report has nothing to do with http://www.jabref.org. Could you please file your bug report against https://github.com/JabRef/jabref/issues? Meanwhile, could you try the latest build from http://builds.jabref.org/master? Could you check Help/Show Error Console and the content of all three tabs? If you repost the issue, the content of that tabs would be helpful!
