### ISSUE TITLE
FAQ: Windows: Q&A to be removed or updated

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#13]
In the windows section of the FAQ, some Q&A seems quite old or to require an update.

#### Q: JabRef does not start on Windows 8, 64bit
A: This has been resolved in JabRef 2.9.1.

==> Quite old... To be removed?

#### Q: My virus-scanner tells me that JabRef is a virus. Is your server compromised?
A: No.
But the windows installer uses [the Nullsoft Scriptable Install System (NSIS)](http://nsis.sourceforge.net/Main_Page) version 2.18 (as of JabRef 2.1) 

==> Even older...  To be removed?

#### Q: How can I use JabRef as backend for Microsoft Word?
A:  [...] The last option is to use [Docear4Word](https://github.com/Docear/Docear4Word), which is planned to be ported to JabRef.

==> What is the current status of https://github.com/JabRef/JabRef4Word ? Shouldn't it be mentioned?

**Comment by matthiasgeiger** [comment]
Regarding the first two 'Q's': Yes, this is obsolete by now.

But I don't know the status regarding Docear/Jabref4Word....

**Comment by koppor** [comment]
JabRef4Word is in planning state. We need developers for it and currently we don't see anyone looking at it.

**Comment by mlep** [comment]
OK, thanks!
