### ISSUE TITLE
Fix failing builds or disable htmlproof

### ISSUE THREAD

**Issue by koppor** [JabRef/www.jabref.org#17]
The tool [HTMLproofer](https://github.com/gjtorikian/html-proofer) checks our page for broken links [on TravisCI](https://travis-ci.org/JabRef/www.jabref.org/builds/107188373). Currently, this does not work well.

- [ ] Some URLs return 0, which indicates some kind of error, but not specified which error (e.g., http://tex.stackexchange.com/tags/jabref/)
- [ ] The link to the source of the page is neither working locally nor on TravisCI. Only on GitHub (e.g., `/blob/gh-pages/_faq/05_intro.md`)

Either we try to fix it or we have to disable htmlproof.

**Comment by mlep** [comment]
I do not know if it is related, but following my last commit (faq), I got the message:



Sujet : [JabRef/www.jabref.org] Page build failure
Date : Fri, 05 Feb 2016 00:31:47 -0800
De : GitHub <support@github.com>

The page build failed with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

If you have any questions you can contact us by replying to this email.

**Comment by koppor** [comment]
I also got that mail. This was because of a missing space. Steps to reproduce locally:

    bundle exec jekyll build

Output:

    Configuration file: c:/git-repositories/jabref/www.jabref.org/_config.yml
                Source: c:/git-repositories/jabref/www.jabref.org
           Destination: c:/git-repositories/jabref/www.jabref.org/_site
     Incremental build: disabled. Enable with --incremental
          Generating...
                 Fatal: Invalid YAML front matter in c:/git-repositories/jabref/www.jabref.org/paypal.html

**Comment by koppor** [comment]
html proof disabled.  We are currently trying to focus on other things. :fire:
We will come back later to this topic and thus closing the issue for now.
