### ISSUE TITLE
Add FAQ for file renaming

### ISSUE THREAD

**Issue by koppor** [JabRef/www.jabref.org#20]
One can rename a file using the cleanup functionality.

"One thing to note is that you can change the format(pattern) under Import in the Preferences. Then under the Default PDF file link action you can designate the Filename format pattern." (From https://sourceforge.net/p/jabref/mailman/message/34830638/)

**Comment by mlep** [comment]
FAQ added.
See : https://github.com/JabRef/www.jabref.org/commit/972a5fe69eca6e7a105e9d3e7170b08d14cb4f0d
