### ISSUE TITLE
Add screenshots?

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#21]
- *Observation 1*: Currently, there is no screenshot of the JabRef GUI on the website.
- *Observation 2*: A few screenshots (V 3.0) are on the old (sourceforge) wiki: http://sourceforge.net/p/jabref/wiki/Main_Page/ , so they are not easy to access
- *Observation 3*: screenshots on wikipedia are outdated (https://commons.wikimedia.org/w/index.php?title=Special%3ASearch&profile=default&search=jabref+screenshot&fulltext=Search&uselang=en )

Hence, it is difficult for potential users to see what JabRef looks like before making their decision to try it.

I believe we need to add up-to-date screenshots in an visible place.
Do you agree?

In such a case:
- Which place?
     - www.jabref.org? (where?)
     - Wikipedia?
     - Other?
- Which screenshots?
     - Which windows?
     - Screenshots from different OS? (some users are sensitive to a good visual integration)

**Comment by simonharrer** [comment]
:+1: 

Place: mainly jabref.org
OS: at least one for each operating system (windows, linux, Mac OSX)
What: not sure, to keep it simple I would suggest focusing on the most important use case: having a library loaded in the default configuration, and editing an entry.

**Comment by tobiasdiez** [comment]
Good idea to add screenshots. I would manly make screenshots of windows which are at least somewhat visually appealing. There should be images for every 2-3 features listed on jabref.org. I like the integration of screenshots and text on [xamarin](http://xamarin.com/).

**Comment by koppor** [comment]
@matthiasgeiger You made the screenshots for https://sourceforge.net/projects/jabref/. Do you think, it's possible to migrate them? Could you take care?

**Comment by matthiasgeiger** [comment]
"Migrate" to v3.2 or place them on jabref.org? 

The latter would require some time as I am not firm with those jekyll templating system and how to add js libs etc. to show the screenshots nicely...

**Comment by mlep** [comment]
BTW, I can make screenshot for Linux, when needed.

**Comment by koppor** [comment]
@matthiasgeiger If you have the HTML code, I can easily integrate it in the homepage.

We should make the screnshots reproducible. The JabRef settings and the bib file should be versioned somewhere. Proposal: https://github.com/JabRef/jabref/tree/master/src/test/resources/screenshots. Alternatively, we could version them here in the master branch. This is possibly less confusing.

**Comment by koppor** [comment]
@matthiasgeiger Just put "screenshots.html" in the root in the `gh-pages` branch and I can integrate that snippet into the layout.

**Comment by matthiasgeiger** [comment]
Might be a good work for friday afternoon ;-)

**Comment by mlep** [comment]
About reproducible screenshots:
- An example of BibTeX file is available here: https://www.ctan.org/tex-archive/biblio/bibtex/contrib/test  (file test.bib).
- For a BibLaTeX file, see https://www.ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex

Maybe they could also be useful to ensure JabRef compatibility during its development?

**Comment by koppor** [comment]
@mlep: Could you please add the links to https://github.com/JabRef/jabref/wiki/Publicly-available-BibTeX-files?

I think, we should create our own bib file showing the most features of JabRef.

**Comment by tobiasdiez** [comment]
Can the new GUI tests be used to make screenshots? Then we could automatically create up-to-date shoots after every release.

**Comment by mlep** [comment]
@koppor: done!

**Comment by andlaus** [comment]
I looked at the website and I have a few additional comments:

- there's no mentioning of the license. If I my only contact point with the project was the current homepage, I'd think that JabRef is some free as in beer binary-only crapware.
- there's no link to the source tarballs of releases and the link to the github repo is quite obscure
- the developer's mailing list is not linked from the website. is it inactive?
- the mailing list archive is not directly linked and the one referred to by the 'General Support -> mailing list' page is the crappy one which mailman provides. referring people over gmane.org (i.e.,http://dir.gmane.org/gmane.comp.java.jabref.user )  would already be a huge improvement IMO.

All of these points are all pretty small issues, but if I was looking for a citation database manager, they could easily be dealbreakers for me. That said, I quite like the design of the website...

**Comment by oscargus** [comment]
@andlaus: relevant points! Regarding the developer mailing list we decided to abandon it a few days ago as it is not used anyway (all discussions are here on GitHub). (I would assume that the persons working more actively on the website take your input into consideration. Small but clearly relevant and easy to fix.)

**Comment by koppor** [comment]
I close this issue as we have screenshots.

@andlaus Your comments will be noted elsewhere to keep this issue tracker clean.

**Comment by koppor** [comment]
@andlaus Thank you for the gmane pointer, we will move away from mailinglists to discourse: http://discourse.jabref.org/
