### ISSUE TITLE
Alexa report about www.jabref.org

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#22]
From http://www.alexa.com/siteinfo/jabref.org : 
- Most visitors from US and Germany (confirming the 2015 survey results)
- 2/3 of visitors coming from sourceforge.net .
- 8% of visitors are coming from a search engine (using a seach for "jabref")

 It will be interesting to see how these 2 figures evolve

Issue ready to be closed. ;-)

**Comment by koppor** [comment]
![grabbed_20160211-232821](https://cloud.githubusercontent.com/assets/1366654/12992844/267a8410-d117-11e5-84e4-82291b7b7980.png)

Maybe I should install [AWStats](http://www.awstats.org/) or [visitors](http://www.hping.org/visitors/).

Damn, this will work for builds.jabref.org only. For www.jabref.org, we will have to use Alexa Pro, [Google Analytics](https://www.google.com/analytics/), or something else. Alternatively, I could host it on a dedicated server, but I am afraid of possible downtimes.

**Comment by simonharrer** [comment]
Why not simply use Google Analytics?

**Comment by stefan-kolb** [comment]
:+1: for Google analytics if you are really interested in the stats.

**Comment by koppor** [comment]
Google Analytics: Privacy concerns - [at least in Germany](https://de.wikipedia.org/wiki/Google_Analytics#Datenschutz_von_Benutzerprofilen). I suppose, however, that persons taking care for privacy will install [Privacy Badger](https://www.eff.org/privacybadger) or [similar tools](https://disconnect.me/) even though [it seems to have issues with Google Analytics](https://github.com/EFForg/privacybadgerfirefox/issues/298).

**Comment by koppor** [comment]
Fun fact: [our theme](https://github.com/t413/SinglePaged) already has built-in support for Google Analytics. However, it uses the old style and offers no opt-out.

I created an "Impressum" and enabled Google Analytics at c3e30fc. Please write me a private mail if you want to be added to the users of Google Analytics for www.jabref.org.
