### ISSUE TITLE
Add anchors to headings

### ISSUE THREAD

**Issue by koppor** [JabRef/www.jabref.org#24]
In GitHub's wiki, it is possibly to directly link to headings. For instance https://github.com/JabRef/jabref/wiki#usage-information

![grabbed_20160216-151149](https://cloud.githubusercontent.com/assets/1366654/13078492/a0bb70bc-d4bf-11e5-977e-07d3892442bd.png)

This is not possible with default Jekyll. We should enable this for the help site, too. Maybe, this requires building with Jekyll for ourselves and uploading to the `gh-pages` branch. The latter can easily be done as [demonstrated at TSDBCompare](https://github.com/TSDBBench/TSDBCompare/blob/master/.travis.yml).
- [ ] Enable generating anchors to headings in Jekyll
- [ ] Enable generation of the web site on TravisCI and upload to `gh-pages` branch

**Comment by tobiasdiez** [comment]
Should work using a little bit of Javascript, see here: https://milanaryal.com/2015/adding-hover-anchor-links-to-header-on-github-pages-using-jekyll/

**Comment by Siedlerchr** [comment]
This seems to even simpler with the new version:
http://bryanbraun.github.io/anchorjs/

But I have no idea where to include that js stuff in the files.

**Comment by koppor** [comment]
@Siedlerchr Thank you for the pointer. It was easier than expected. I added a quick solution for https://www.jabref.org and https://help.jabref.org. My solution would IMHO also work without JavaScript, but it seems to be difficult, especially after reading https://milanaryal.com/adding-hover-anchor-links-to-header-on-github-pages-using-jekyll/#jquery-and-font-awesome-alternative
