### ISSUE TITLE
Simplify click path to Download

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/www.jabref.org#25]
I'm not really satisfied with current situation regarding downloading JabRef. 

If a user lands on jabref.org there are 3 (or even 4) clicks needed to actually start the download:
Scroll down to the Download section (or click on Download), click "Download now" on the github release page, choose the right file at sourceforge.

Why don't we link directly to https://sourceforge.net/projects/jabref/files/latest/download from jabref.org? Using this link automatically the download of latest version matching to the users OS is started. 

Besides this download link we still can link to the release notes at github.

**Comment by simonharrer** [comment]
:+1:

**Comment by tobiasdiez** [comment]
Or put some icons of the different OS under the "download section" on jabref.org and a click on an icon directly downloads the correct installer without redirecting to the sourceforge download page (direct link to sourceforge download as for example http://downloads.sourceforge.net/project/jabref/v3.2/JabRef_windows_3_2.exe?r=&ts=1455698605&use_mirror=netix [not sure if this link is a permalink]).

**Comment by koppor** [comment]
We are now using [FossHub](http://www.fosshub.com/) and directly link it at http://www.jabref.org/#downloads. Should solve the issues. Although it are still two clicks, users can decide whether they want to get the JAR or the binary.

**Comment by matthiasgeiger** [comment]
:+1: 

One thing: Is it possible to change "Download JabRef Linux BSD Solaris and Others" - which links to the jar - to "Download platform independent runnable jar" (or sth similar?).

**Comment by koppor** [comment]
Text is fixed.
