### ISSUE TITLE
Add blog

### ISSUE THREAD

**Issue by koppor** [JabRef/www.jabref.org#29]
The site should offer a blogging functionality. The most recent entry should be shown at http://www.jabref.org/#news

URL: http://www.jabref.org/blog

**Comment by bruehldev** [comment]
I get a 404 on the URL. In which folder on (https://github.com/JabRef/www.jabref.org) should i upload the blog posts? 
Also are .md tags correct for the uploads?

**Comment by koppor** [comment]
Yes, the `.md` file extension is correct. Thanks @boceckts to provide the initial version of the blogging functionality!
