### ISSUE TITLE
Fix generated link anchors

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#33]
Near the bottom of page http://www.fosshub.com/JabRef.html, there is a line
>Found this software useful? Please consider a donation to the author. "Button Donate"

This links to http://www.jabref.org/#donations, which leads to the top of the page and not to the donation section.
The link should be http://www.jabref.org/#sections50-donations

**Comment by koppor** [comment]
This is because we fixed #29 and thus the anchors are generated differently. I know that [Cool URIs don't change](https://www.w3.org/Provider/Style/URI), but I hadn't the time to dive into the topic.

We have to investigate the Jekyll generation further.

**Comment by mlep** [comment]
For the record: same thing here: http://jabref.sourceforge.net/contact.php

**Comment by koppor** [comment]
What is the issue with http://jabref.sourceforge.net/contact.php? It redirects to http://www.jabref.org/#help, which is displayed as programmed in the template.

**Comment by koppor** [comment]
I fixed this issue at a9847adbc3c6730bc56, so I would vote to close this one.

**Comment by mlep** [comment]
Cannot find it anymore... Sorry...
