### ISSUE TITLE
Migrate resources.php

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#34]
In the previous design of the website, there was a page listing additional resources (https://web.archive.org/web/20150208123147/http://jabref.sourceforge.net/resources.php).
I believe we should have a page for this.
If you agree: where should it be located?

**Comment by oscargus** [comment]
I think a new page on www.jabref.org

Much of the stuff can be removed though. Plugins, most of the export filters (which are already included), ...

**Comment by mlep** [comment]
OK, thanks. There is surely a need for cleaning the old list!

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/111

**Comment by koppor** [comment]
Refs https://github.com/JabRef/reference-abbreviations/issues/12
