### ISSUE TITLE
[Blog's post] A faster JabRef

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#35]
Following https://github.com/JabRef/jabref/pull/1100 , I figure out this is a more suitable place for a discussion.

**Please, review (facts and writing) at PR #37.**

Tentative publication date : Friday April 8  (a week before the post about the release of version 3.3).

%%%%%%%%%%%%%%%%%%%%%%%%%%

# A faster JabRef is coming!

Some users reported JabRef was slow on large databases (thank you for the feedback!). This was especially the case for three operations:
- loading a database
- saving a database
- searching through a database.

During a search, the user interface could become very unresponsive, which is indeed quite annoying... Well, this time will be over soon: @simonharrer has recently contributed code making search much faster (https://github.com/JabRef/jabref/pull/1100). By integrating the Java Microbenchmarking framework (https://github.com/JabRef/jabref/pull/1103), @tobiasdiez was able to benchmark JabRef and reveal interesting insights about the performance of JabRef:

Preliminary tests have been carried out on a database with 100000 entries (is it big enough for you?). They show that JabRef is now 10 times faster at searching: it takes only one second to search through 60000 entries.

If you want to give it a try: http://builds.jabref.org/master/ **(this is a development version. So, be carefully, and back up your data!)**. Your comments are welcomed at https://github.com/JabRef/jabref/pull/1100

*About opening large databases:* work is under way to speed it up You can follow this development at https://github.com/JabRef/jabref/issues/1094

**Comment by mlep** [comment]
I have tried to convert this into a pull request (which seems more appropriate). 
Clicking on "New pull request" led me to https://github.com/JabRef/www.jabref.org/compare .
I am probably missing something...

**Comment by simonharrer** [comment]
Go to https://github.com/JabRef/www.jabref.org/new/gh-pages/_posts and then click on "new file" add the contents and then it is turned into a PR, I think.

**Comment by mlep** [comment]
@simonharrer: Thanks for the pointer. It works.
Comments and changes welcomed at PR #37.

**Comment by koppor** [comment]
Follow up at #37.
