### ISSUE TITLE
Project of blog post:  Highlighting of differences in merge entries

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#47]
I am planning to write a blog post about the feature "Added highlighting of differences in merge entries dialogs and made s… #1022" (https://github.com/JabRef/jabref/pull/1022).

The goals are:
- to present this coming feature (with screenshots)
- to show users that JabRef development never stops
- to ask users for testing this new feature and give feedback (especially about the preferred difference mode)

Intended release around May 10.

Comments and ideas welcome (before I start writing a first draft; to be submitted as an issue).

**Comment by koppor** [comment]
I will try to move the blog to http://blog.jabref.org due to url consistency reasons with http://help.jabref.org. I hope to have this finished this week.

**Comment by mlep** [comment]
No hurry!

**Comment by mlep** [comment]
@koppor Before I make the pull request for this post, could you, please, send to the mailing list the previous post (JabRef & WinEdt)?

**Comment by mlep** [comment]
Too late...

**Comment by koppor** [comment]
Ups. We now have the forum for that - does that work?
