### ISSUE TITLE
Cool gif showcasing the cool features of JabRef

### ISSUE THREAD

**Issue by simonharrer** [JabRef/www.jabref.org#49]
Something similar to https://www.sublimetext.com/ which showcases special features, e.g., the Integrity Check, DOI search and get Document by DOI feature, etc.

**Comment by Siedlerchr** [comment]
I think the easiest way would be do a Screenrecording and then converting that video to a gif.

**Comment by koppor** [comment]
I made good experiences with https://chocolatey.org/packages/screentogif

**Comment by tobiasdiez** [comment]
The website already has pictures demonstrating the most important features. While it would be nice to show them in action, I think this would also create to much visual noise (most landing pages I've seen work with static images). Maybe it would be good to have a short "getting started" video in the documentation.

In either case, there hasn't been any progress on this in the last 5 years, so let's close it (PRs are still welcome of course).
