### ISSUE TITLE
Add HTTPS Support for website

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/www.jabref.org#52]
Google Ranks websites with HTTPS support higher.
More info on why HTTPS 
https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

@koppor Can https be configured?

**Comment by koppor** [comment]
I'm planning to continue use GitHub to host the pages. Thus, it won't be possible to use https. See https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8 and https://github.com/isaacs/github/issues/156.

If we really want to have https, we can use my own server with all the pros and cons. Currently, I feel unable to keep a production server up and running 24/7; and I currently don't want to spend the donations on alternative hosting.

**Comment by Siedlerchr** [comment]
There has been an update to the state:  Github now works together with CloudFare, thus supporting SSL:
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by matthiasgeiger** [comment]
Great that is already working now!

@koppor Is it also possible to enable https for http://discourse.jabref.org/ ?

**Comment by koppor** [comment]
I enabled discourse on cloudflare, but it does not work. Nevertheless closing this issue as all other sites are https enabled now.
