### ISSUE TITLE
JavaScript broken

### ISSUE THREAD

**Issue by simonharrer** [JabRef/www.jabref.org#53]
JS is broken currently.

**Comment by koppor** [comment]
@JabRef/developers anyone else having issues? - I reloaded with CTRL+SHIFT+r and everyhting works fine here.

The symptoms seemed to be that click on "Download" does not scroll down to the downloads. Here, on latest Firefox and Chrome, everything works fine!

**Comment by simonharrer** [comment]
Seems to be fixed now
