### ISSUE TITLE
Add alias for github pages

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/www.jabref.org#60]
Can we add alias pages to some of the direct github pages. For example,

- issues.jabref.org -> https://github.com/JabRef/jabref/issues
- code.jabref.org -> https://github.com/JabRef/jabref

I think it looks slightly better to refer someone to "post the problem at issues.jabref.org" instead of some github url which for a normal person has nothing to do with issues or jabref. (Slight bonus: maybe get a better pagerank)

**Comment by koppor** [comment]
Done add https://github.com/JabRef/issues.jabref.org and https://github.com/JabRef/code.jabref.org

Feel free to edit the appropriate places at https://github.com/JabRef/www.jabref.org and https://github.com/JabRef/help.jabref.org/
