### ISSUE TITLE
Width of FAQ page weird

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/www.jabref.org#62]
Firefox latest version, when I click on my mousewheel to fast scroll, I am able to scroll to the left, and the FAQ Contents move left, creating a white area on the right.

Seems like there is some fixed with problem or whatever

![jabreffaqwidth](https://cloud.githubusercontent.com/assets/320228/18915400/265b6ac4-8591-11e6-9298-77a3e212cd50.png)

**Comment by mlep** [comment]
The FAQ is going to become an help page: https://github.com/JabRef/www.jabref.org/pull/59

**Comment by mlep** [comment]
I have open a specific issue: https://github.com/JabRef/www.jabref.org/issues/64
