### ISSUE TITLE
Remove FAQ from www.jabref.org/FAQ

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#64]
The FAQ is now part of the help pages (https://help.jabref.org/en/), so:
- [x] the link in the Help section of the website (https://www.jabref.org/#help) should be updated
- [x] the URL http://www.jabref.org/faq/ should redirect to the help page index (https://help.jabref.org/en/)

**Comment by Siedlerchr** [comment]
I removed the FAQ from the Website section and added a redirect link to http://help.jabref.org/
