### ISSUE TITLE
Ressources: status of OpenOffice style files?

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#72]
Considering http://discourse.jabref.org/t/referencing-styles-specifically-harvard/260 , I am wondering what is the status of the following OpenOffice style files http://jabref.sourceforge.net/OOPlugin-styles.php , and so if they should be included in the Resources page.

**Comment by Siedlerchr** [comment]
Maybe @oscargus  can help answering that question. i do not know if the styles still work

**Comment by tobiasdiez** [comment]
The resources page now moved to the help, and I think you resolved this issue in your latest revision anyway.
