### ISSUE TITLE
Direct URL to a (sub)section?

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#76]
I would like to have an URL that could lead directly, for example, to the section "JabRef journal abbreviation lists" of the resources' page (www.jabref.org/#resources).

Is it possible? How?

**Comment by Siedlerchr** [comment]
Currently not, but we could have these anchors like at the help pages
@koppor

2016-12-09 17:55 GMT+01:00 MLEP <notifications@github.com>:

**Comment by tobiasdiez** [comment]
Links to sections are not implemented, e.g. http://www.jabref.org/#getinvolved
