### ISSUE TITLE
Update homepage with release of 4.0

### ISSUE THREAD

**Issue by lenhard** [JabRef/www.jabref.org#79]
This is just to track that we need to do a few documentation updates when we release 4.0.

The first thing that comes to my mind are the screenshots of JabRef that we show at the top of our homepage here: http://www.jabref.org/ The entry editor looks new and that should be reflected.

**Comment by LinusDietz** [comment]
fixed in da0257e4782fb1d28490a55cd73f1eef9e4d549b, b781f2cc3a3b9a5fa480941406c20b74aa918a13, and accae700c73d62b79e35dc95c8bdff0f18600c33
