### ISSUE TITLE
Remove GitHub corner

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#80]
When browsing the help (https://help.jabref.org/), clicking on the mascot at the upper right-hand corner leads to the edit page of the help. For example, if you are at https://help.jabref.org/en/FAQlinux , you go to https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/FAQlinux.md .

This is not the case for the website (http://www.jabref.org/): it leads to the JabRef source code (https://github.com/JabRef/jabref) instead of  the website code (https://github.com/JabRef/www.jabref.org).

Maybe it is a feature, but I was surprised about it.

**Comment by koppor** [comment]
Going to the GitHub project is the usual setting for projects.

The idea behind the different links is:

1. www.jabref.org is a landing page for JabRef interested guys
2. all other pages are pages for people knowing more about JabRef.

Thus, corner link at help was that the more experienced users going there.

I can change everything to go to the GitHub project page as we have the "Edit this page" link at the bottom.

**Comment by mlep** [comment]
So it is a feature! ;-)

**Comment by tobiasdiez** [comment]
Personally, I would remove the icon from the main page completely. I don't think that an average user knows what github is and our page here is definitely not a good landing page for a new user. Just add the link to github under `Contributing` and the few guys that look for a coding opportunity still find us :-).
(By the way, I also don't like the Flattr button...it just don't fits into the design and gives no real benefit in my eyes.)

Can you also add a tooltip in the help pages to the github icon saying that this leads to the `Edit` page? And when we are at improvements, is it possible to change the link from 
- view on github: https://github.com/JabRef/help.jabref.org/blob/gh-pages/index.md
to
- edit on github: https://github.com/JabRef/help.jabref.org/edit/gh-pages/index.md

**Comment by tobiasdiez** [comment]
The github link now moved to the footer.
