### ISSUE TITLE
Old JabRef icon in browser tab

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#81]
The old JabRef icon is displayed in the browser tab.

**Comment by Siedlerchr** [comment]
I replaced the icons here and in blog. If the old icon is still shown then it may be still in your browser cache

**Comment by mlep** [comment]
👍 +1

**Comment by tobiasdiez** [comment]
Actually, for me no icon is shown on the main page as well as on the blog. http://www.jabref.org/facvicon.ico leads to a 404 error page. Is this just temporary?

**Comment by Siedlerchr** [comment]
In Firefox it's no longer shown in the address bar, but on the tab itself
Took me a moment to realize this

Am 23.09.2017 1:15 vorm. schrieb "Tobias Diez" <notifications@github.com>:

**Comment by tobiasdiez** [comment]
@Siedlerchr no there was really a typo in the icon name, but its fixed now.
