### ISSUE TITLE
Create gource.io video for JabRef code

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/www.jabref.org#83]
http://gource.io/

There is already a video which captures the dev up to 2015:
https://www.youtube.com/watch?v=WFXNmAKG6vA 

Tips on how to create a video:
https://github.com/acaudwell/Gource/wiki/Videos

**Comment by koppor** [comment]
More recent gource: https://www.youtube.com/watch?v=cFuZnzq97sQ

**Comment by tobiasdiez** [comment]
That might be a valuable addition for the dev docs, but not for the main page. Thus let's close this.
