### ISSUE TITLE
Tools for Android outdated

### ISSUE THREAD

**Issue by reox** [JabRef/www.jabref.org#90]
https://github.com/JabRef/www.jabref.org/blob/c8ac603f8252d83c456de9dee1bb628a76f8d8d0/_sections/60-Ressources.md shows a link to Eratosthenes.
Unfortunately, it looks like this project is abandoned, at least it is not available on Google Play.

I tried to find an alternative, but from the four Android apps listed here https://tex.stackexchange.com/questions/230278/edit-and-view-bibtex-database-on-android to read BibTeX files, only one is still on Google Play / F-Droid: https://github.com/cgogolin/library

Regarding the other apps:
* RefMaster seems to be out of business, and seems to be not open source (a discussion can be found here: https://latex.org/forum/viewtopic.php?t=20981)
*  Eratosthenes vanished from Google Play, but source is still available: https://bitbucket.org/mkmatlock/eratosthenes/src
* BibRef vanished from Google Play too and does not seem to be open source.

I tested Library and it works with JabRef's .bib files, unfortunately, the display is a bare minimum and the only JabRef feature which is supported are groups, but without the tree view.
But you can open the linked PDFs, search for entries, share the entry and open DOIs.

I dont know if you should still link to Eratosthenes, as there are no binaries but I would certainly like to see Library be mentioned, as it seems to be the only app on Google Play right now which can handle .bib files on Android. If there are other alternatives, please put them there as well :)

**Comment by Siedlerchr** [comment]
Thanks for the research into this topic, I agree with you, this would be helpful for other users as well!
Feel free to directly edit the page here and update the list of tools. 
https://github.com/JabRef/www.jabref.org/blob/master/_sections/60-Ressources.md
