### ISSUE TITLE
Update to jekyll 4

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/www.jabref.org#92]
https://jekyllrb.com/docs/upgrading/3-to-4/

**Comment by koppor** [comment]
Could you please refine the issue?

Facts:

* We use github actions to deploy the page: https://github.com/JabRef/www.jabref.org/blob/master/.github/workflows/publish.yml
* We use our fork of the github action: https://github.com/koppor/jekyll-deploy-gh-pages
* The action itself already supports Jekyll 4 (see https://github.com/BryanSchuetz/jekyll-deploy-gh-pages/issues/5)

I remember that a simple update was not possible as not all plugins of Jekyll are available for 4.0. Should I document that further?

What are your wishes regarding the update to 4.0? Is there something disturbing at the web page or its build? Maybe, you could enlight me here (and maybe provide a pull request fixing these issues). - In case it is just at the sake of using newer versions, I would skip it as we have so many other open issues.

**Comment by Siedlerchr** [comment]
It was just a reminder that we at some point in the future should  update to it. Not necessarily now.
