### ISSUE TITLE
Give facelift

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/www.jabref.org#98]
The design of our webpage need a facelift in my opinion.

- Templates:
	- https://y7kim.github.io/agency-jekyll-theme/
	- https://jekyllthemes.io/theme/creative-theme-jekyll
	- http://shaneweng.com/landing-page-theme/
	- https://jekyllthemes.io/theme/landing-page-theme
	- https://jekyllthemes.io/theme/hydra-jekyll-theme
	
-  inspiration
	- --> https://junolab.org/
        - --> https://www.google.com/chrome/
	- http://www.styleshout.com/demo/?theme=lhander
	- http://electron.atom.io/
	- https://code.visualstudio.com/
	- https://www.drawboard.com/pdf/
        - https://getmemex.com/
	- https://chocolatey.org/
	- https://getpocket.com/
	- https://www.hubspot.com/crm/e010a?utm_content=e010a&utm_source=facebook.com&utm_campaign=Facebook-IntNonEngSpeaking-AllLaLs-2P-AllSegs-Desktop&utm_medium=paid&utm_term=crm&utm_id=e616a4v4
	- -> http://flarum.org/features/
	- -> https://www.amazon.com/b?ie=UTF8&node=16571048011&tag=aboutcom02lifewire-20
	- https://lavalite.org/
	- https://getmusicbee.com/
	- https://www.arduino.cc/en/Main/Software
	- https://todoist.com/
	- https://www.visualstudio.com/vs/#tab-c0c537cf292b435612f
	- https://www.behance.net/gallery/48964477/Landing-Page-Concept
	- https://lingvist.com/
	- https://www.elsevier.com/solutions/pure/who-uses-pure/librarians
	- https://www.citavi.com/en/features.html
	- https://www.shiftyjelly.com/pocketcasts/
	- https://material.io/
	- https://www.zotero.org/
	- https://atom.io/
	- https://lineageos.org/
	- https://ticktick.com/about/windows
	- https://hellonext.co/
	- https://kodi.tv/download
        - -> https://typora.io/
	- -> https://www.notion.so/product
        - -> https://www.mendeley.com/guides/mendeley-reference-manager

Pictures:
- https://www.ahmetertug.com/works/libraries/

**Comment by tobiasdiez** [comment]
Done in https://github.com/JabRef/www.jabref.org/pull/100

**Comment by Siedlerchr** [comment]
We should tackle the blog next
![Screenshot_20200523_153002](https://user-images.githubusercontent.com/320228/82731925-5173d180-9d0a-11ea-91f5-ecf79aa72d2d.jpg)

**Comment by tobiasdiez** [comment]
Good point. 
In principle, this would be easy as one could reuse most of the code. However, the blog is currently in a different repo which makes code reuse hard (without copy-paste). What's the reason for the different repo? @koppor  If it is ok to move the blog content to this repo here and some git wizard is so nice to import the blog posts (with git history?) here, then I'll take care of the design.
